name: tests

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  linting:
    name: Check Linting
    runs-on: ubuntu-latest
    steps:
      - uses: neuroinformatics-unit/actions/lint@v2

  manifest:
    name: Check Manifest
    runs-on: ubuntu-latest
    steps:
      - uses: neuroinformatics-unit/actions/check_manifest@v2

  test:
    needs: [linting, manifest]
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Run across a mixture of Python versions and operating systems
        include:
        - os: ubuntu-latest
          python-version: "3.11"
        - os: macos-latest
          python-version: "3.10"
        - os: windows-latest
          python-version: "3.9"

    steps:
      - uses: neuroinformatics-unit/actions/test@v2
        with:
          python-version: ${{ matrix.python-version }}
